### PR TITLE
added retry with delay for http get

### PR DESCRIPTION
**Pull request by romain894**
When downloading a long list of elements from OpenAlex, I got a few errors. I added some code to retry to get the data from the API and it solved the problem.
Probably not the best way to program it, but it doesn't need any new package except "time" and it's working great.

### CODE REVIEW

**Comment by J535D165** [comment]
Interesting!

Do you know the http status of the failed requests? Is it 429? And which pool are you using?

**Comment by romain894** [comment]
I don't remember the http error but I could try again to reproduce the error. I was using the polite pool.

**Comment by J535D165** [comment]
It makes sense to delay when the server returns 429. Other codes should raise in my opinion or the bugs should get resolved on the OpenAlex side. So if we can get an overview of the errors, that would be great. 

If you share the code here as well, I can also run a test.

**Comment by lfoppiano** [comment]
I would also add the error 503, which also indicate that the server may be overloaded.
I'm not sure this could work with the paginating cursor, though. 

Example of my issue: 

```
Traceback (most recent call last):
  File "/Users/lfoppiano/development/projects/concepts-visualisation/concepts_visualisation/openalex/fetch.py", line 17, in <module>
    for page in tqdm(pager):
  File "/Users/lfoppiano/anaconda3/envs/nii/lib/python3.10/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/Users/lfoppiano/anaconda3/envs/nii/lib/python3.10/site-packages/pyalex/api.py", line 176, in __next__
    r, m = self.alex_class.get(
  File "/Users/lfoppiano/anaconda3/envs/nii/lib/python3.10/site-packages/pyalex/api.py", line 281, in get
    res.raise_for_status()
  File "/Users/lfoppiano/anaconda3/envs/nii/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: [...]
```

**Comment by romain894** [comment]
I reproduced the error and I got the error 500 (internal server error):
```bash
$ sudo docker run -i test-pyalex
  8%|▊         | 792400/9870321 [1:47:41<20:33:41, 122.64it/s]
Traceback (most recent call last):
  File "//test.py", line 14, in <module>
    for page in pager:
  File "/usr/local/lib/python3.10/site-packages/pyalex/api.py", line 176, in __next__
    r, m = self.alex_class.get(
  File "/usr/local/lib/python3.10/site-packages/pyalex/api.py", line 281, in get
    res.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://api.openalex.org/works?filter=concepts.id:C18903297&per-page=200&cursor=Ils0MCwgJ2h0dHBzOi8vb3BlbmFsZXgub3JnL1cyMDI0Mzc1NjQxJ10i
```
The code used to test:
```python
from pyalex import Works
from tqdm import tqdm

query = {"concepts": {"id": "C18903297"}}
per_page = 200

# get the number of entities to download
results, meta = Works().filter(**query).get(per_page = 1, return_meta=True)
n_entities = meta['count']

pager = Works().filter(**query).paginate(per_page = per_page, n_max = None)

with tqdm(total=n_entities) as pbar:
    for page in pager:
        for entitie in page:
            pass
        # update the progress bar
        pbar.update(per_page)

```
The code is here: [test_pyalex_bug.zip](https://github.com/J535D165/pyalex/files/11759892/test_pyalex_bug.zip)

**Comment by lfoppiano** [comment]
For the definition, 500 indidcate an internal error of the application. 

https://developer.mozilla.org/en-US/docs/web/http/status/500

So we should not treat is as the API is overloaded. However, it seems that with this API may be also the case, which is not so good because it indicate a design flaw.

**Comment by romain894** [comment]
I don't understand why the problem could be the API overloaded as the program is making less than a request per second (which is way below the maximum of 10 per second).

This problem appeared the 3 times I tried to get this set of works and at the beginning (before 20% if I remember well). It could be worth running this same test with the same and other queries to see if the problem arises at the same page.

**Comment by lfoppiano** [comment]
Either that or there are internal problems with the openalex API. 
In my short experience I've seen different rate of 503 in different days. 
By the way, how do you know it's doing less than one request per second? I don't see any timer in your code.

**Comment by romain894** [comment]
I'm using tqdm on the for loop and you can see it's retrieving 122.64 works per second (so less than a request of 200 per second).

I did several other smaller requests and I don't remember having this error.

**Comment by J535D165** [comment]
Usually, I don't like to handle internal server errors as non-deterministic, however, your example shows that this limits us as end users. 

I'm thinking about the following interface (in line with this PR). By default, `max_retries` is 0. 
```python

pyalex.config.max_retries = 0
pyalex.config.retry_delay = 1
pyalex.config.retry_http_codes = [503, 429]

```

In this way, we can easily go back to the default behavior and see if OpenAlex improved their internals. 

Btw, there is also an option to write a `retry` function. You can use this function to wrap up your request. I have seen this in other libs. However, this might make the syntax a bit too complex for some users. 

Let me know what you think.

**Pull request closed without merging**
